sudo: false  # Not needing sudo enables container builds.

addons:
  apt:
    sources:
    - sourceline: 'deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8'
      key_url: 'https://bazel.build/bazel-release.pub.gpg'
    - sourceline: 'ppa:marutter/rrutter'
    packages:
    - bazel
    - r-recommended

cache:
  directories:
    - $HOME/.cache/bazel
before_cache:
  # Do not cache the install directory of bazel
  - rm -rf $HOME/.cache/bazel/_bazel_travis/install

script:
  - cd tests
    # Run periodic tests with a clean cache
  - if [[ "${TRAVIS_EVENT_TYPE}" == 'cron' ]]; then bazel clean --expunge; fi
  - bazel test --color=yes --show_progress_rate_limit=30 --keep_going --test_output=errors //...
  - ./binary/execution_tests.sh
