sudo: false  # Not needing sudo enables container builds.

os:
  - linux
  - osx

osx_image: xcode9.3

addons:
  apt:
    sources:
    - sourceline: 'deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8'
      key_url: 'https://bazel.build/bazel-release.pub.gpg'
    - sourceline: 'ppa:marutter/rrutter3.5'
    packages:
    - bazel
    - r-recommended

before_install:
  # brew r does not quite work.
  # Track R version on macOS to be the same major version as from apt.
  # When updating major version, also update CRAN package versions for compatibility.
  # Also, try to upgrade python to python3.
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        wget https://cloud.r-project.org/bin/macosx/R-3.6.0.pkg -O /tmp/R.pkg &&
        sudo installer -pkg "/tmp/R.pkg" -target / &&
        rm "/tmp/R.pkg" &&
        ( brew upgrade python || true ) &&
        brew tap bazelbuild/tap &&
        brew install bazelbuild/tap/bazel;
    fi

script:
  - tests/run_tests.sh
